In [2]:
import torch as t

a = t.tensor([1, 2, 3])
b = t.tensor([4, 5, 6])
print(a + b)

tensor([5, 7, 9])


In [3]:
# A 3d tensor
a = t.randn(3, 4, 5)
print(a)
print(a.shape)

tensor([[[-0.2249, -1.3403,  0.8512,  0.5682,  0.8250],
         [-0.3840,  0.4010, -2.8834,  1.3349,  0.7833],
         [ 0.6281, -0.5914,  0.6253, -0.7030, -0.7286],
         [ 0.1499,  1.1123, -0.7711, -0.8897, -1.9449]],

        [[ 1.1906,  2.1959, -0.8232,  1.6257,  0.9740],
         [ 0.1936, -0.9523,  1.1778,  0.2221,  0.0674],
         [ 0.0363, -0.1834, -0.2101, -1.4521, -0.5406],
         [-0.6944,  1.5248,  0.1768,  0.1865,  1.0392]],

        [[ 1.4371,  0.2831,  0.7265,  0.2472, -0.0163],
         [-0.4742,  0.1355,  0.0636,  2.1007,  0.0270],
         [-0.8650,  0.6416,  0.8745,  1.2852, -1.0647],
         [-0.5630,  0.8975, -0.9010, -0.1361, -0.2429]]])
torch.Size([3, 4, 5])


In [4]:
x = t.tensor([0., 0., 1., 0., 0.])
x.shape

torch.Size([5])

In [5]:
a @ x

tensor([[ 0.8512, -2.8834,  0.6253, -0.7711],
        [-0.8232,  1.1778, -0.2101,  0.1768],
        [ 0.7265,  0.0636,  0.8745, -0.9010]])