In [4]:
import numpy as np

r = np.array([1/3, 1/3, 1/3])
M = np.array([[0  , 1/2, 1], 
              [1/2, 1/2, 0], 
              [1/2,   0, 0]]
            )

for _ in range(100):
    r = np.matmul(M, r)
    print(r)

[0.5        0.33333333 0.16666667]
[0.33333333 0.41666667 0.25      ]
[0.45833333 0.375      0.16666667]
[0.35416667 0.41666667 0.22916667]
[0.4375     0.38541667 0.17708333]
[0.36979167 0.41145833 0.21875   ]
[0.42447917 0.390625   0.18489583]
[0.38020833 0.40755208 0.21223958]
[0.41601562 0.39388021 0.19010417]
[0.38704427 0.40494792 0.20800781]
[0.41048177 0.39599609 0.19352214]
[0.39152018 0.40323893 0.20524089]
[0.40686035 0.39737956 0.19576009]
[0.39444987 0.40211995 0.20343018]
[0.40449015 0.39828491 0.19722493]
[0.39636739 0.40138753 0.20224508]
[0.40293884 0.39887746 0.1981837 ]
[0.39762243 0.40090815 0.20146942]
[0.4019235  0.39926529 0.19881121]
[0.39844386 0.40059439 0.20096175]
[0.40125895 0.39951913 0.19922193]
[0.39898149 0.40038904 0.20062947]
[0.40082399 0.39968526 0.19949075]
[0.39933338 0.40025463 0.200412  ]
[0.40053931 0.399794   0.19966669]
[0.39956369 0.40016666 0.20026965]
[0.40035298 0.39986517 0.19978185]
[0.39971443 0.40010908 0.20017649]
[0.40023103 0.399911